import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/src/providers/QueryProvider";
import Sidebar from "@/src/components/layout/Sidebar";
import Navbar from "@/src/components/layout/Navbar";
import {Toaster} from 'react-hot-toast'
export const dynamic = 'force-dynamic'

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.className}>
      <body
        className={`${poppins.variable} overflow-hidden`}>
        <QueryProvider>
          <Toaster position="top-right" reverseOrder={true} />
          <Sidebar />
          <div className="ml-62.25 overflow-y-auto overflow-x-hidden h-screen">
            <Navbar />
            {children}
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}